### ISSUE TITLE
Connection Pooling issues when using MySQL

### ISSUE THREAD

**Issue by SteveClement** [cuckoobox/cuckoo#442]
Dear,

I had to bump the pool_size in: https://github.com/cuckoobox/cuckoo/blob/master/lib/cuckoo/core/database.py for the MySQL connection (which is a fall-through if… yep rather ugly)

This fixed it: self.engine = create_engine(connection_string, pool_size=50, max_overflow=-1)

Default seems to be, pool_size=5 max_overflow=10 (-1 disables max overflow)

This was the Issue in Debug:

2015-01-21 16:13:33,849 [lib.cuckoo.core.database] DEBUG: Database error fetching task: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30

More infos on pooling: http://docs.sqlalchemy.org/en/rel_0_7/core/pooling.html

Take good care and thanks for your support :)

**Comment by jekil** [comment]
I can confirm, i am working on this since yesterday. It happen with postgres too

**Comment by jekil** [comment]
Should be solved now. I hope someone can test it in an high load installation.

**Comment by SteveClement** [comment]
Is not solved. Again, it is a pooling issue with connections TO the dbServer.

**Comment by jekil** [comment]
I got the some error with postgresql and #dc36ecf fixed. If the issue is still present on you setup please provide more details (how many concurrent analysis, mysql release, if the error occur every analysis, and so on). I will re-test it on mysql.

**Comment by rep** [comment]
There must be some other issue / problem, the max_overflow parameter is definitely not a problem in that sense. Basically regardless of pool_size or max_overflow, SQLA will wait for a connection in the pool to be available for some time (default 30 sec I think). Only after that it will give up. This means that your setup basically was using 10 connections to the database, and not giving any of them back for 30 seconds. This should really never happen with our Cuckoo database usage patterns, there must be some other issue with your setup.

Also in addition we made some changes to the database class, in fact right now all the database access should be serialized - we merely use SQLA for its abstraction, not for any pooling performance right now.
